### ISSUE TITLE
Documentation Not Updated for Django 3.0.3

### ISSUE THREAD

**Issue by pakauffm** [edcrewe/django-csvimport#101]
Newer version of django are either unsupported or the documentation doesn't explain how to install properly.

**Comment by edcrewe** [comment]
Hi, Thanks for letting me know. Just fixing for Django 3. Will add a new version that supports it.

**Comment by edcrewe** [comment]
OK this should be fixed in django-csvimport 2.15
See README for update to tested version and details for installing messytables if you need to use the inspectcsv command to generate models.
