### ISSUE TITLE
2.16 test fixes

### ISSUE THREAD

**Issue by edcrewe** [edcrewe/django-csvimport#103]
- Strip out all test tables from default migrations
- Add separate migrations for tests and separate settings - or check if Django test database can work for this,ie test table creation using in memory sqlite only for running tests. Should never get test tables create by migrate after csvimport install
- Fix all the tests and remove try except since it can hide broken tests
- Add regression tests for all new issue fixes 
- Add issue98 test and model
- Add fix for inspectcsv generating model with empty types using issue98 table (default to char type and max length of field)
- Retest that the tests pass in older django 2.* or add version check and code switch so that they do
- Add test for passing in encoding on admin form to test that issue

**Comment by io-ma** [comment]
Hi,
Any chance [this one](https://github.com/edcrewe/django-csvimport/issues/98) is solved in 2.16?
Just about to import a 1500 lines CSV so will probably write a script to add commas at the end of each row. 
Thank you lots!

**Comment by edcrewe** [comment]
Yes sure I will add a test and fix for that issue.

**Comment by edcrewe** [comment]
Sorry test cannot replicate issue ... it is not an issue anybody else has reported. Unfortunately I cannot fix a bug that I cannot replicate. Completed all the other changes so closing this issue.
