### ISSUE TITLE
Error testing with gitlab-ci a django app with django-csvimport as an installed_app

### ISSUE THREAD

**Issue by gfunosas** [edcrewe/django-csvimport#105]
Hello!

Nice work! 
We coped with an issue that may be worth some attention.

When testing our django application, that has `django-csvimport` as an installed_app (settings.py), with gitlab-ci (continuous integration) we run into this error:
```
$ coverage run manage.py test -v 2
(...)
psycopg2.errors.UndefinedTable: relation "csvtests_issue98" does not exist
LINE 1: ...id", "csvtests_issue98"."co_total_comp_high" FROM "csvtests_...
```
As indicated in the [here](https://github.com/edcrewe/django-csvimport#installation-instructions):
> Note that migrate has the core tables in 0001_initial migration and test tables in 0002 so rm migrations/0002_test_models.py if you do not want these cluttering your database

The file `0002_[...].py` contains data for the tests which is not present by default, but that is required when building the test database for testing the django application that uses django-csvimport. Therefore, if we don't run the `makemigrations` command, or we remove this file as suggested in your instructions, we can also run into the same error locally (it will happen always when missing the second migration file). 

As a workaround solution, we can execute tests in gitlab-ci with different settings, without `csvimport.app.CSVImportConf` in INSTALLED_APPS. 

Would you recommend another approach, or know any other project with django-csvimport as a dependency that has found a better solution for this?
Also, which steps would you follow to define a testing pipeline? Would the makemigrations command be a required step?

Thank you,

**Comment by edcrewe** [comment]
Sorry I failed to respond to your query.
The approach I would recommend is that you shouldn't be testing all third party apps, or running django's own tests.
You should only need to test your own code and applications. That is the only coverage that is relevant.
For example use ...

./coverage run django-admin test --settings='yourapp.settings' yourapp.tests -v 2
