### ISSUE TITLE
Error when importing csv file with only one row

### ISSUE THREAD

**Issue by Cordelya** [edcrewe/django-csvimport#106]
I was doing simple one-table importing via the Admin site interface. I encountered an error a few times where the system threw a debug error page ('int' object has no attribute 'decode') when attempting to import certain .csv files and I just figured out what they all had in common: each file only had one row. I can work around this and will include it in my local documentation, but I thought you'd want to hear about it.

**Comment by io-ma** [comment]
Encountered the same problem, here's the last part of the traceback:

<img width="787" alt="Screenshot 2021-11-03 at 19 01 42" src="https://user-images.githubusercontent.com/2306628/140148235-ac3c7197-0f02-4504-bcac-30311fb6db36.png">

**Comment by ezawadzki** [comment]
Same here.

**Comment by edcrewe** [comment]
Sorry I failed to respond to your ticket.

I will add a test for import of a single row to check this issue.

**Comment by edcrewe** [comment]
OK added test_single_row.csv with extra line returns at the end and replicated the issue.

**Comment by edcrewe** [comment]
OK fixed the issue
