### ISSUE TITLE
Being able to override separator in the import csv form

### ISSUE THREAD

**Issue by edouard-gv** [edcrewe/django-csvimport#107]
Requirements: for certain localization, the csv separator is not the comma (eg. in France, it is the semi-column). Export in excel files, for instance, use this localized separator. Note that a raw replace in the file won't work, for excel, still, only put double quotes around data fields that contains the separator.

Proposed solution:
- adding a field in the model, and passing it to the setup
- default value in the form: the one that could be set in the local (not sure if it's feasible)
- default value in database: "," in order for older GUI import to work, for older import defined in the GUI had "," as separator.

**Comment by edouard-gv** [comment]
(I'm working on it)

**Comment by edcrewe** [comment]
Sorry I failed to respond to your ticket.

CSV import already has this feature. See the README example for using a tab as the delimiter (= csv separator)

manage.py importcsv --mappings='' --model='app_label.model_name' --delimiter='\t' importfile.csv
