### ISSUE TITLE
Removing test from package

### ISSUE THREAD

**Issue by juleswaldhart** [edcrewe/django-csvimport#115]
Real nice work here.
I think it would be nice to remove tests from the PyPi package.

I'm installing csvimport through pip, using latest version of csvimport (2.16).
As it have been reported (#105) there is a problem with csvimport wanting to run tests when running `manage.py test` on my django project. This is clearly undesired. Same problem occurs with makemigrations, which I don't want to create migrations for csvimport, as I don't want to run its tests. ( plus, makemigrations fails because of csvimport, I didn't dig further to the cause, I just don't want to makemigrations for csvimport anyway)

I think the fix would be to get the `tests` directory outside of `csvimport` directory. But I don't know what the implications would be on the whole project.

**Comment by edcrewe** [comment]
Sorry I failed to respond to your ticket.

This would happen to you for all third party packages you install. The solution is not to remove tests from everyone else's packages. It is just to only specify your own for testing and migrations ...

django-admin test --settings=yourapp.settings yourapp.tests

Similarly for migrations

django-admin migrate yourapp_label
