### ISSUE TITLE
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'

### ISSUE THREAD

**Issue by Nindenkawe** [edcrewe/django-csvimport#117]
Having trouble after pip install and adding to apps 
![image](https://user-images.githubusercontent.com/87611829/154186049-3fef0a0d-364a-4825-a47b-28cc96d792d6.png)

cant eve make migrations same error re appears kindly help

**Comment by frabyn** [comment]
Looks like providing_args was deprecated in 3.1 and removed in 4.0

https://docs.djangoproject.com/en/4.0/releases/3.1/#deprecated-features-3-1
