### ISSUE TITLE
Package not working with Python 3.12

### ISSUE THREAD

**Issue by antonnichtaustirol** [edcrewe/django-csvimport#118]
Using Python 3.12 this package is currently not working.

The problem is an import from `distutils`, which has been remove from python 3.12.

Import is taking place here:
https://github.com/edcrewe/django-csvimport/blob/5edab101eb6e172221c8ae730e7afacc07254a42/csvimport/management/commands/importcsv.py#L10 

Deprecation warning can be seen here:
https://docs.python.org/3.11/library/distutils.html

**Comment by antonnichtaustirol** [comment]
It's recommended to use `packaging.Version` instead: https://github.com/pypa/packaging/issues/520

**Comment by antonnichtaustirol** [comment]
Error cannot not be reproduced anymore after reinstalling all pip packages. Issue therfore closed.

**Comment by gregsadetsky** [comment]
I'm having this exact error/problem - can't use this with Python 3.12.3 because of the failed "distutils" import unfortunately
