### ISSUE TITLE
Can't import tables with empty foreign key fields

### ISSUE THREAD

**Issue by dzirique** [edcrewe/django-csvimport#28]
I'm trying to import a csv file which contains a foreign key reference. In the model, the foreign key field is set to "blank=True, null=True" to make sure the reference may be empty. Now, when I import a csv file that contains only data with a FK id filled in, everything works fine. But when the csv file contains a line with an empty FK reference, I get an error: invalid literal for int() with base 10: '' (or 'NULL' if I try to insert a null value directly.) Obviously, the program is trying to assign a string to an integer field while creating the foreign key reference.

From looking at the code in csvimport.py, it seems to me that the insert_fkey function always tries to insert a reference in the "if not matches" clause, no matter if the passed value has the correct datatype. I'd suggest checking the datatypes explicitly, and if they don't match, checking whether the value passed from the csv file is either an empty string or 'NULL', and if so, simply leaving the foreign key field empty. (I've tried fixing this myself, but I can't seem to get it to work, but then I'm only a beginner with Python...)

**Comment by edcrewe** [comment]
I believe this is already fixed having tested it out and not been able to replicate
