### ISSUE TITLE
Type Error while uploading GroupedForeignKey model

### ISSUE THREAD

**Issue by raj115** [edcrewe/django-csvimport#29]
I am using django-csvimport to populate my mysql database ,but i am running into a Type Error when importing data into a GroupedForeignKey Field with following message 

TypeError at /admin/csvimport/csvimport/add/

not all arguments converted during string formatting

Request Method:     POST
Request URL:    http://127.0.0.1:8000/admin/csvimport/csvimport/add/

Type Error is only occurring while importing data into a field with GroupedForeignKey.

Model = GroupedForeignKey('masters.Model', "MClass")

What can be the possible solution?

**Comment by edcrewe** [comment]
Please see the reply to 
https://github.com/edcrewe/django-csvimport/issues/40

The same thing applies. You would need to generate a temporary model with 
inspectcsv importfile.csv > models.py
then populate it with the lookup data for each of the columns that are in the grouped foreign key
added as separate standard data columns, then write a bulk insert that could manage querying the correct ids and populating the final model tables appropriately from this temporary csvimport populated table.

The ForeignKey handling is basic and is really for vocabulary data, where the id relates to one unique searchable field.

Ed
