### ISSUE TITLE
Rows not imported still increment primary key

### ISSUE THREAD

**Issue by 1beb** [edcrewe/django-csvimport#30]
I'm not sure why but rows that can't be imported still increment the primary key of a database. So importing a file with 50k records where 20k where not importable, would have primary keys from 1-50k.

**Comment by edcrewe** [comment]
Hi I have added a test for a file with unparsable rows in it, and not found this to be the case.
It would suggest that it may be a database / schema specific issue, ie. dajngo adds the row, but the database has constraints that block row insertion for invalid data after incrementing the primary key sequence for that table.
