### ISSUE TITLE
csv.reader - set optional delimiter (e.g. semicolon)

### ISSUE THREAD

**Issue by radeksvarz** [edcrewe/django-csvimport#31]
CSV files are delimited either by comma or by semicolon. 

Please, provide the option to set semicolon delimiter.

I had to fix manually the file cvsimport.py line 379:

```
     csv_reader = csv.reader(self.charset_encoder(csv_data, charset),
                            dialect=dialect, delimiter=";", **kwargs)  
```

**Comment by edcrewe** [comment]
OK done with --delimiter=';'
