### ISSUE TITLE
sudo pip install django-csvimport==2.1 produces broken csvimport module.

### ISSUE THREAD

**Issue by rrothwell** [edcrewe/django-csvimport#51]
It appears that the fix for issue: "setup tools losing csvimport/**init**.py on install"
has not been propagated to the Python package Index here: https://pypi.python.org/pypi/django-csvimport.

**Comment by rrothwell** [comment]
In other words __init__.py is missing from the top level csvimport directory she installing via pip for version 2.1.

**Comment by edcrewe** [comment]
FIxed in version 2.2 and later (currently 2.5)
