### ISSUE TITLE
Several import issues

### ISSUE THREAD

**Issue by bmeyer71** [edcrewe/django-csvimport#53]
I've run into several problems actually.
I'm using Django 1.7.2 and python3.4.
If there is a header line in the csv file, it will not import either from the commandline or in the Admin. Unless I add mappings to the Admin import, it will not import. With the mappings added, it will only import the first line.
From the commandline, when adding the mappings to the import command it imports the first line, but then seems to go into an infinite loop.

Not sure what's happening here. Any suggestions are appreciated.

Update: forgot to mention I am using commit 464ab20371aa9f5df75aef50a9194a69d1b46a48 of django-csvimport

**Comment by edcrewe** [comment]
Hi I believe I have fixed these issues in the new version 2.5. Although I have not been able to replicate the header only issue, the infinite loop was related to a recursive call with the command line usage.
Please let me know if any of the problems remain. I will package this up for release on pypi today.
