### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by nachogl** [edcrewe/django-csvimport#58]
When trying to import a CSV file and after click on save.i got an error.  (I am using sqllite database)

Any help please?

Request Method:
POST 

Request URL:
http://127.0.0.1:8000/admin/csvimport/csvimport/add/ 

Django Version:
1.8.3 

Exception Type:
TransactionManagementError 

Exception Value:
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

Exception Location:
C:\Python33\lib\site-packages\django-1.8.3-py3.3.egg\django\db\backends\base\base.py in validate_no_broken_transaction, line 327 

Python Executable:
C:\Python33\python.exe 

Python Version:
3.3.5 

No GET data

POST

Variable

Value

csrfmiddlewaretoken 'By10k4mnlFE6vHNsMeeMgciAger46Lt6'

model_name 'polls.Question'

_save 'Save'

field_list 'column1=Question text,column2=Date_published'

encoding ''

FILES

Variable

Value

upload_file <InMemoryUploadedFile: test.csv (application/vnd.ms-excel)>

COOKIES

Variable

Value

sessionid '53pqt8vra8nmyx9mulzwkulpwro43gt3'

csrftoken 'By10k4mnlFE6vHNsMeeMgciAger46Lt6'

**Comment by chrisalcantara** [comment]
BUMP

**Comment by Jufik** [comment]
Same here!

**Comment by harshit298** [comment]
facing same issue after django upgrade to 1.8

**Comment by LMHudson** [comment]
similar issue. trying to upload a csv file from the admin form results in:
Request Method:	POST
Request URL:	http://localhost:8000/admin/csvimport/csvimport/add/
Django Version:	1.9.8
Exception Type:	ProgrammingError
Exception Value:	
relation "csvimport_csvimport" does not exist
LINE 1: INSERT INTO "csvimport_csvimport" ("model_name", "field_list...
                    ^
Exception Location:	/Users/lawrencemhudson/Documents/django/testenv/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/Users/lawrencemhudson/Documents/django/testenv/bin/python
Python Version:	3.4.3
Python Path:	
['/Users/lawrencemhudson/Documents/django/pa',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload',
 '/Users/lawrencemhudson/Documents/django/testenv/lib/python3.4/site-packages']
Server time:	Tue, 23 Aug 2016 10:31:52 -0700

**Comment by edcrewe** [comment]
Hi,

Merged in some fixes and add more for version 2.5

Just tested this and it all worked fine for the test fixture file - eg. Error log html field has ...
Columns = CODE_SHARE, CODE_ORG, ORGANISATION, DESCRIPTION, UOM, QUANTITY, STATUS
Using mapping from first row of CSV file
Imported 8 rows to Item
and the rows are in the database.

Note that if the table csvimport_csvimport is not found then you need to run either syncdb or migrate depending on your django version (ie. migrate or migrate csvimport for 1.9) 
Versions of csvimport prior to 2.5 need you to run makemigrations csvimport too.

Foreign keys are supported but if your database has foreign key constraints you may need to populate the tables in the correct FKey dependency sequence

**Comment by shameelabdulla** [comment]
For many models it is working. but not working for the following model:

class AppReview(models.Model):
	"""Class with review"""
	app_name = models.CharField(max_length = 255)
	review_date = models.DateTimeField()
	review_title = models.CharField(max_length = 255)
	review_content = models.TextField()
	reviewer_name = models.CharField(max_length = 255)
	device_type = models.CharField(max_length = 255)
	review_rating = models.FloatField()
	
	date_added = models.DateTimeField(auto_now_add=True)


	

	def __str__(self):
		"""Return a string representation of the model."""
		return self.app_name
