### ISSUE TITLE
DATE_INPUT_FORMATS is now a list instead of a tuple (Django 1.9)

### ISSUE THREAD

**Issue by called2voyage** [edcrewe/django-csvimport#61]
When attempting to import a CSV, I get a TypeError "can only concatenate list (not "tuple") to list". The Traceback shows that csvimport/management/commands/importcsv.py is attempting to perform this:

`CSV_DATE_INPUT_FORMATS = DATE_INPUT_FORMATS + ('%d-%m-%Y', '%Y-%m-%d')`

In Django 1.9, DATE_INPUT_FORMATS is a list, so this operation is invalid.

**Comment by pratiklodha95** [comment]
do you have any workaround for now ?

**Comment by selloutdesign** [comment]
Nothing on this? I can't get it to work.

**Comment by called2voyage** [comment]
Hold on, let me find my workaround.

**Comment by called2voyage** [comment]
Workaround: CSV_DATE_INPUT_FORMATS = DATE_INPUT_FORMATS + ['%d-%m-%Y','%Y-%m-%d']
