### ISSUE TITLE
BaseCommand.option_list removed in Django 1.10

### ISSUE THREAD

**Issue by adevore** [edcrewe/django-csvimport#67]
The upcoming Django 1.10 release has removed support for BaseCommand.option_list. Instead, a new add_arguments() method has been added starting in 1.8. inspectcsv and importcsv need to be adjusted to use add_arguments() where available. I can add in a version hack for Django 1.7 or support for Django 1.7 can be removed in the next release.

**Comment by edcrewe** [comment]
Fix was merged and tested with 1.10
