### ISSUE TITLE
django.db.models...  is deprecated for django 1.8

### ISSUE THREAD

**Issue by IBibik** [edcrewe/django-csvimport#71]
> 
> C:\Users\PAPA\DEV\rent_unit\rent_unit_venv\lib\site-packages\csvimport\models.py:26: RemovedInDjango19Warning: django.db.models.get_models is deprecated. allmodels = models.get_models()
> 
> C:\Users\PAPA\DEV\rent_unit\rent_unit_venv\lib\site-packages\django\db\models\__init__.py:55:
> RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system. from . import loading
> 
> C:\Users\PAPA\DEV\rent_unit\rent_unit_venv\lib\site-packages\csvimport\models.py:26:
> RemovedInDjango19Warning: django.db.models.get_models is deprecated. allmodels = models.get_models()
> 
> C:\Users\PAPA\DEV\rent_unit\rent_unit_venv\lib\site-packages\django\db\models\__init__.py:55:
> RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system. from . import loading

**Comment by edcrewe** [comment]
Ok this was just because it was trying the old syntax first before the new one in csvimport/models.py - I have now reversed that so you shouldnt see deprecation warnings (the code has multi-version compatibility try except in it)
