### ISSUE TITLE
'Unrecognized arguments' on Python 3.5.2 and Django 1.10

### ISSUE THREAD

**Issue by gitanupam** [edcrewe/django-csvimport#73]
I get the error `unrecognized arguments` and `mappings` doesnt seem to be a valid option in the usage list. Am I missing something?

```
python manage.py importcsv --mappings=’column1=name,column2=some_id,column3=something_else’ --model='peoplelisting.People' --delimiter=',' All_copy.csv
usage: manage.py importcsv [-h] [--version] [-v {0,1,2,3}]
                           [--settings SETTINGS] [--pythonpath PYTHONPATH]
                           [--traceback] [--no-color]
                           label [label ...]
manage.py importcsv: error: unrecognized arguments: --mappings=’column1=name,column2=some_id,column3=something_else’ --model='peoplelisting.People' --delimiter=',
```

Thanks in advance
Anupam

**Comment by edcrewe** [comment]
Hi, Yes very sorry - I just realised the fix for changes to the command options parsing changes for 1.10 no longer works for latest 1.10 and 1.11 on python 2 or 3
Thanks a lot for reporting this. Will fix ASAP.

**Comment by edcrewe** [comment]
Ok I think this is fixed in master now. Need to clean up and push in to next release 2.6

**Comment by edcrewe** [comment]
Ready for release
