### ISSUE TITLE
Typo is breaking migration

### ISSUE THREAD

**Issue by dhbahr** [edcrewe/django-csvimport#77]
In https://github.com/edcrewe/django-csvimport/blob/master/csvimport/migrations/0002_test_models.py#L27 the value for "db_table" includes double quotes that break tests hence preventing the `migrate` command to complete successfully

**Comment by cjmabry** [comment]
Ran into this issue as well, here's a quick pull request to fix - #82.

**Comment by edcrewe** [comment]
Ok fixed in 2.12
