### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by IBibik** [edcrewe/django-csvimport#80]
Getting error   list index out of range

1.8
IndexError
list index out of range
/app/.heroku/python/lib/python2.7/site-packages/csvimport/management/commands/importcsv.py in run, line 247
/app/.heroku/python/bin/python
2.7.13
['/app',  '/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python27.zip',  '/app/.heroku/python/lib/python2.7',  '/app/.heroku/python/lib/python2.7/plat-linux2',  '/app/.heroku/python/lib/python2.7/lib-tk',  '/app/.heroku/python/lib/python2.7/lib-old',  '/app/.heroku/python/lib/python2.7/lib-dynload',  '/app/.heroku/python/lib/python2.7/site-packages']

**Comment by IBibik** [comment]
This is the file and line of error - 
csvimport/management/commands/importcsv.py in run

 msg = 'row %s: Column %s = %s couldnt be set for row' % (i, field, row[column])

**Comment by Unpaid-Intern** [comment]
I'm experiencing the same issue. Did you ever find a work around for this @IBibik ?

**Comment by edcrewe** [comment]
Old issue to upgrade / downgrade problem with django 1.8
