### ISSUE TITLE
django.db.utils.ProgrammingError: syntax error at or near "csvtests_country"

### ISSUE THREAD

**Issue by charliedontsurf** [edcrewe/django-csvimport#83]
[scratch_8.txt](https://github.com/edcrewe/django-csvimport/files/1425022/scratch_8.txt)

Very simple Django project. My import of data works perfectly fine, however whenever I have the  'csvimport.app.CSVImportConf', enabled in settings.py, I get the attached message when I do migrate.

It's not really causing me a problem per se, as the data DOES import. However it is annoying have errors blasting at me every time I try and migrate my django project.

**Comment by edcrewe** [comment]
OK sure thanks, have accepted the commit. May not get released until more significant functional change goes in though.

Ed
