### ISSUE TITLE
Django 2 requires on_delete in models.py

### ISSUE THREAD

**Issue by tdxdave** [edcrewe/django-csvimport#85]
File "/lib/python3.5/site-packages/csvimport/models.py", line 70, in <module>
    class ImportModel(models.Model):
  File "/lib/python3.5/site-packages/csvimport/models.py", line 72, in ImportModel
    csvimport = models.ForeignKey(CSVImport)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by matt-dalton** [comment]
+1 on this

**Comment by anothercwsmith** [comment]
I'm having the same issue:
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by Trajamsmith** [comment]
+1, same error as dave and cw

**Comment by jdnrg** [comment]
found a patch thefreakingmind12/django-csvimport
https://github.com/thefreakingmind12/django-csvimport/commit/117c892390fc6c939127095d69821fb03ef2d96a

**Comment by edcrewe** [comment]
OK fixed in 2.12
