### ISSUE TITLE
Additional (wrong) column for inspectcsv

### ISSUE THREAD

**Issue by SportsTribution** [edcrewe/django-csvimport#95]
Hello, sorry if it's my mistake, I'm new to this
I tried the inspectcsv function, but it gave me an additional column due to the linebreak
python manage.py inspectcsv output/countries.csv

(I added a few prints to the inspectcsv.py)
cols = self.csvfile[0]
        print(cols) 

['name', 'code', 'latitude', 'longitude', 'alias', 'some', 'other', 'data', 'that', 'we', 'dont', 'have', 'in', 'our', '"model"\r', '\n']

The result is:
inspectcsv.py, line 118, in create_new_model
    if types[i] == 'String' and length > 255:
IndexError: list index out of range

So far I couldn't figure out a good solution by myself (sorry)
All the best
Hannes

**Comment by io-ma** [comment]
Hi, 
I am having the same issue. I don't have a model setup for a CSV that I want to import. Trying to use python manage.py inspectcsv name.csv and I get: 
File "/usr/local/lib/python3.6/site-packages/csvimport/management/commands/inspect.csv.py, line 135, in get_maxlengths
if value and len(value) > maximums[i]:
IndexError: list index out of range
I'd fix it if I knew how :-)

**Comment by edcrewe** [comment]
Hi,

Sorry for the slow response. 
I get the same error with a latest python 3.7.3 django 2.2.5, I believe it is a change in csv handling which is producing an empty extra column at the end, which I need to clean up. So I will look into fixing this bug.

Thanks,
Ed

**Comment by io-ma** [comment]
That would be awesome! Thank you so much, I still think this library is exactly what I need for my use case. I am working on the other tasks and leave the CSV import for laters.

**Comment by edcrewe** [comment]
OK this is fixed in master. I will do a new release.

**Comment by io-ma** [comment]
That was quick!
Wish I could buy you 10 beers!
Thank you so much!

**Comment by edcrewe** [comment]
OK its released as 2.13
