### ISSUE TITLE
Why delete encoding on upload?

### ISSUE THREAD

**Issue by zivkovic** [edcrewe/django-csvimport#97]
When adding csv file from admin interface the encoding is always overriden with an empty string. Why is that?

The line in question is located in admin.py:39 (`obj.encoding = ''`)
```   def save_model(self, request, obj, form, change):
        """ Do save and process command - cant commit False
            since then file wont be found for reopening via right charset
        """
        form.save()
        from csvimport.management.commands.importcsv import Command
        cmd = Command()
        if obj.upload_file:
            obj.file_name = obj.upload_file.name
            obj.encoding = '' # LINE IN QUESTION
            defaults = self.filename_defaults(obj.file_name)
            cmd.setup(mappings=obj.field_list,
                      modelname=obj.model_name,
                      charset=obj.encoding,
                      uploaded=obj.upload_file,
                      defaults=defaults)
        errors = cmd.run(logid=obj.id)
```

Is there any specific reasoning for this, or is this just an overlooked issue?

**Comment by edcrewe** [comment]
Hi,

Thanks for spotting this, I guess I haven't included tests that submit via the admin form - they all use the custom importcsv command directly like command line usage does, and hence it has gone unnoticed. From looking at the git logs, I think it may date from before the encoding was included in the admin form TBH.

I have removed the line in master.

Thanks,
Ed

**Comment by zivkovic** [comment]
No problem, glad it is fixed.
