### ISSUE TITLE
final column of import showing as null?

### ISSUE THREAD

**Issue by generationloss** [edcrewe/django-csvimport#98]
Hi -

we're using django-csvimport 2.13.0 with django 2.2.3 and Python 3.8.1.  The csvimport tool works great, except that the final column always shows up as all nulls - a formatting thing, maybe?  A sample csv is pasted below:

co_id,co_role,co_level,co_region,tm_role,tm_level,tm_region,co_salary_low,co_salary_mid,co_salary_high,co_equity_low,co_equity_mid,co_equity_high,co_bonus_low,co_bonus_mid,co_bonus_high,co_total_comp_low,co_total_comp_mid,co_total_comp_high
abcd190,Software Engineer,1,San Francisco,Software Engineer,2,San Francisco,"$100,000","$115,000","$132,250","$20,000","$24,000","$28,800",15%,15%,15%,"$135,000","$156,250","$180,888"
abcd190,Software Engineer,2,San Francisco,Software Engineer,3,San Francisco,"$115,000","$132,500","$152,500","$26,000","$30,000","$40,000",15%,15%,15%,"$158,250","$182,375","$215,375"
abcd190,Software Engineer,3,San Francisco,Software Engineer,4,San Francisco,"$132,500","$152,500","$175,500","$34,000","$40,000","$50,000",15%,15%,15%,"$186,375","$215,375","$251,825"
abcd190,Software Engineer,4,San Francisco,Software Engineer,4.5,San Francisco,"$152,500","$175,500","$202,000","$44,000","$50,000","$60,000",15%,15%,15%,"$219,375","$251,825","$292,300"
abcd190,Software Engineer,5,San Francisco,Software Engineer,5,San Francisco,"$175,500","$202,000","$232,500","$57,000","$70,000","$80,000",20%,20%,20%,"$267,600","$312,400","$359,000"
abcd190,Software Engineer,6,San Francisco,Software Engineer,5.3,San Francisco,"$202,000","$232,500","$267,500","$74,000","$90,000","$110,000",20%,20%,20%,"$316,400","$369,000","$431,000"
abcd190,Software Engineer,7,San Francisco,Software Engineer,5.6,San Francisco,"$232,500","$267,500","$307,500","$96,000","$120,000","$140,000",25%,25%,25%,"$386,625","$454,375","$524,375"
abcd190,Software Engineer,8,San Francisco,Software Engineer,6,San Francisco,"$267,500","$307,500","$353,500","$125,000","$150,000","$180,000",25%,25%,25%,"$459,375","$534,375","$621,875"
abcd190,Researcher,1,San Francisco,Data Science,2,San Francisco,"$90,000","$103,500","$119,025","$15,000","$18,000","$21,600",15%,15%,15%,"$118,500","$137,025","$158,479"
abcd190,Researcher,2,San Francisco,Data Science,3,San Francisco,"$103,500","$119,000","$137,000","$20,000","$24,000","$28,800",15%,15%,15%,"$139,025","$160,850","$186,350"
abcd190,Researcher,3,San Francisco,Data Science,4,San Francisco,"$119,000","$137,000","$157,500","$26,000","$31,200","$37,440",15%,15%,15%,"$162,850","$188,750","$218,565"
abcd190,Researcher,4,San Francisco,Data Science,4.5,San Francisco,"$137,000","$157,500","$181,000","$34,000","$40,800","$48,960",15%,15%,15%,"$191,550","$221,925","$257,110"
abcd190,Researcher,5,San Francisco,Data Science,5,San Francisco,"$157,500","$181,000","$208,000","$44,000","$52,800","$63,360",20%,20%,20%,"$233,000","$270,000","$312,960"
abcd190,Researcher,6,San Francisco,Data Science,5.3,San Francisco,"$181,000","$208,000","$239,000","$57,000","$68,400","$82,080",20%,20%,20%,"$274,200","$318,000","$368,880"
abcd190,Researcher,7,San Francisco,Data Science,5.6,San Francisco,"$208,000","$239,000","$275,000","$74,000","$88,800","$106,560",25%,25%,25%,"$334,000","$387,550","$450,310"
abcd190,Researcher,8,San Francisco,Data Science,6,San Francisco,"$239,000","$275,000","$316,500","$96,000","$115,200","$138,240",25%,25%,25%,"$394,750","$458,950","$533,865"
abcd190,Data Science,1,San Francisco,Data Analyst,1,San Francisco,"$80,000","$92,000","$105,800","$10,000","$12,000","$14,400",15%,15%,15%,"$102,000","$117,800","$136,070"
abcd190,Data Science,2,San Francisco,Data Analyst,2,San Francisco,"$92,000","$106,000","$121,500","$13,000","$15,600","$18,720",15%,15%,15%,"$118,800","$137,500","$158,445"
abcd190,Data Science,3,San Francisco,Data Analyst,3,San Francisco,"$106,000","$122,000","$139,500","$17,000","$20,400","$24,480",15%,15%,15%,"$138,900","$160,700","$184,905"
abcd190,Data Science,4,San Francisco,Data Analyst,4,San Francisco,"$122,000","$140,500","$160,500","$22,000","$26,400","$31,680",15%,15%,15%,"$162,300","$187,975","$216,255"
abcd190,Data Science,5,San Francisco,Data Analyst,4.5,San Francisco,"$140,500","$161,500","$184,500","$29,000","$34,800","$41,760",15%,15%,15%,"$190,575","$220,525","$253,935"
abcd190,Data Science,6,San Francisco,Data Analyst,5,San Francisco,"$161,500","$185,500","$212,000","$38,000","$45,600","$54,720",15%,15%,15%,"$223,725","$258,925","$298,520"
abcd190,Data Science,7,San Francisco,Data Analyst,5.5,San Francisco,"$185,500","$213,500","$244,000","$49,000","$58,800","$70,560",20%,20%,20%,"$271,600","$315,000","$363,360"
abcd190,Data Science,8,San Francisco,Data Analyst,6,San Francisco,"$213,500","$245,500","$280,500","$64,000","$76,800","$92,160",20%,20%,20%,"$320,200","$371,400","$428,760"
abcd190,App Design,1,San Francisco,Product Designer,2,San Francisco,"$110,000","$126,500","$145,475","$20,000","$24,000","$28,800",15%,15%,15%,"$146,500","$169,475","$196,096"
abcd190,App Design,2,San Francisco,Product Designer,3,San Francisco,"$126,500","$145,500","$167,500","$26,000","$31,200","$37,440",15%,15%,15%,"$171,475","$198,525","$230,065"
abcd190,App Design,3,San Francisco,Product Designer,4,San Francisco,"$145,500","$167,500","$192,500","$34,000","$40,800","$48,960",15%,15%,15%,"$201,325","$233,425","$270,335"
abcd190,App Design,4,San Francisco,Product Designer,4.5,San Francisco,"$167,500","$192,500","$221,500","$44,000","$52,800","$63,360",15%,15%,15%,"$236,625","$274,175","$318,085"
abcd190,App Design,5,San Francisco,Product Designer,5,San Francisco,"$192,500","$221,500","$254,500","$57,000","$68,400","$82,080",20%,20%,20%,"$288,000","$334,200","$387,480"
abcd190,App Design,6,San Francisco,Product Designer,5.3,San Francisco,"$221,500","$254,500","$292,500","$74,000","$88,800","$106,560",20%,20%,20%,"$339,800","$394,200","$457,560"
abcd190,App Design,7,San Francisco,Product Designer,5.6,San Francisco,"$254,500","$292,500","$336,500","$96,000","$115,200","$138,240",25%,25%,25%,"$414,125","$480,825","$558,865"
abcd190,App Design,8,San Francisco,Product Designer,6,San Francisco,"$292,500","$336,500","$387,000","$125,000","$150,000","$180,000",25%,25%,25%,"$490,625","$570,625","$663,750"

**Comment by charliedontsurf** [comment]
Could it be as simple as missing a comma at end of final column?

**Comment by io-ma** [comment]
Hmmm, I am in the same team with @generationloss , let me try that.
Thank you for answering!

**Comment by edcrewe** [comment]
Note added issue_tests.py to add tests for regressions - ie reported bugs.
Added reported model and csv file to check this.
Cannot replicate the problem, test passes - so not sure how this issue occurred unless it is platform related, unfortunately I don't have access to Windows to test this. So closing bug.
